name: Hello Workflow
 
on:
  push:
 
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Siwakorn Phimpanit
        run: echo "สวัสดี GitHub Actions!"
      - name: Show date
        run: date
      - name: Show machine info
        run: uname -a
